/*
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */

/*
 * Libraries
 */
__LIBRARIES__

/*
 * Modules
 */
__MODULES__

/*
 * Module class definition
 */
class __MODULECLASSNAME__{
private:
/*
 * Global variables
 */
__GLOBALVARS__

/*
 * Inner classes
 */
__HANDLERS__


public:
/*
 * Events declaration
 */
__EVENTDECL__

/*
 * Constructor
 */
__MODULECLASSNAME__(){
	/*
	 * Events allocation
	 */
	__EVENTINIT__
}

~__MODULECLASSNAME__(){
	/*
	 * Events deallcoation
	 */
	__EVENTDELETE__
}

/*
 * Module's body
 */
int main(){
	__INIT__
	return 0;
}

};
