/*
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */

/*
 * Libraries
 */
__LIBRARIES__

/*
 * Modules
 */
__MODULES__

/*
 * Struct def
 */
__MAINSTRUCTDEF__

int main()
{
/*
 * Events declarations
 */
__EVENTS__

/*
 * Handlers declarations
 */
__HANDLERS__

/*
 * Init section
 */
__INIT__

return 0;
}
