/**
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */
#include "__HANDLERCLASSNAME__.h"

__HANDLERCLASSNAME__::__HANDLERCLASSNAME__() {}

__HANDLERCLASSNAME__::~__HANDLERCLASSNAME__() {}

void __HANDLERCLASSNAME__::update(void* args) {
/*
 * downcast of parameters from void* args
 */
__HANDLERPARAMSCAST__

/*
 * handler's body
 */
__HANDLERBODY__

}
