/**
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */
#ifndef __UPPERHANDLERCLASSNAME___H
#define	__UPPERHANDLERCLASSNAME___H

#include <iostream>
#include "Handler.h"

class __HANDLERCLASSNAME__ : public Handler {
public:
	__HANDLERCLASSNAME__();
    ~__HANDLERCLASSNAME__();
    void update(void* args);
};

#endif	/* __UPPERHANDLERCLASSNAME___H */
