/**
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */
#ifndef __HANDLERCLASSNAME___H
#define	__HANDLERCLASSNAME___H

#include <iostream>
#include "Handler.h"

class __HANDLERCLASSNAME__ : public Handler {
public:
	__HANDLERCLASSNAME__();
    ~__HANDLERCLASSNAME__();
    void update(int arg);
};

#endif	/* __HANDLERCLASSNAME___H */
