/**
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */
#include "__HANDLERCLASSNAME__.h"

__HANDLERCLASSNAME__::__HANDLERCLASSNAME__() {}

__HANDLERCLASSNAME__::~__HANDLERCLASSNAME__() {}

void __HANDLERCLASSNAME__::update(__HANDLERPARAMS__) {
	__HANDLERBODY__
}
