/*
* generated by Xtext
*/

package org.mt.lic.eol.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class EventOrientedLanguageGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_0 = (UnorderedGroup)cGroup.eContents().get(0);
		private final Assignment cGlobalsAssignment_0_0 = (Assignment)cUnorderedGroup_0.eContents().get(0);
		private final RuleCall cGlobalsGlobalSectionParserRuleCall_0_0_0 = (RuleCall)cGlobalsAssignment_0_0.eContents().get(0);
		private final Assignment cEventsAssignment_0_1 = (Assignment)cUnorderedGroup_0.eContents().get(1);
		private final RuleCall cEventsEventSectionParserRuleCall_0_1_0 = (RuleCall)cEventsAssignment_0_1.eContents().get(0);
		private final Assignment cHandlersAssignment_0_2 = (Assignment)cUnorderedGroup_0.eContents().get(2);
		private final RuleCall cHandlersHandlerSectionParserRuleCall_0_2_0 = (RuleCall)cHandlersAssignment_0_2.eContents().get(0);
		private final Keyword cInitKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInitAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInitAbstractBlockParserRuleCall_2_0 = (RuleCall)cInitAssignment_2.eContents().get(0);
		private final Keyword cEndKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		/// *
		// * Main structure of a program. Global variables, events and handlers can be declared
		// * in any order but sections must stay separated. The init section must be the last one
		// * and it is mandatory.
		// * /Program:
		//	(globals=GlobalSection? & events=EventSection? & handlers=HandlerSection?) "init:" init=AbstractBlock "end";
		public ParserRule getRule() { return rule; }

		//(globals=GlobalSection? & events=EventSection? & handlers=HandlerSection?) "init:" init=AbstractBlock "end"
		public Group getGroup() { return cGroup; }

		//globals=GlobalSection? & events=EventSection? & handlers=HandlerSection?
		public UnorderedGroup getUnorderedGroup_0() { return cUnorderedGroup_0; }

		//globals=GlobalSection?
		public Assignment getGlobalsAssignment_0_0() { return cGlobalsAssignment_0_0; }

		//GlobalSection
		public RuleCall getGlobalsGlobalSectionParserRuleCall_0_0_0() { return cGlobalsGlobalSectionParserRuleCall_0_0_0; }

		//events=EventSection?
		public Assignment getEventsAssignment_0_1() { return cEventsAssignment_0_1; }

		//EventSection
		public RuleCall getEventsEventSectionParserRuleCall_0_1_0() { return cEventsEventSectionParserRuleCall_0_1_0; }

		//handlers=HandlerSection?
		public Assignment getHandlersAssignment_0_2() { return cHandlersAssignment_0_2; }

		//HandlerSection
		public RuleCall getHandlersHandlerSectionParserRuleCall_0_2_0() { return cHandlersHandlerSectionParserRuleCall_0_2_0; }

		//"init:"
		public Keyword getInitKeyword_1() { return cInitKeyword_1; }

		//init=AbstractBlock
		public Assignment getInitAssignment_2() { return cInitAssignment_2; }

		//AbstractBlock
		public RuleCall getInitAbstractBlockParserRuleCall_2_0() { return cInitAbstractBlockParserRuleCall_2_0; }

		//"end"
		public Keyword getEndKeyword_3() { return cEndKeyword_3; }
	}

	public class GlobalSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GlobalSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlobalsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cGlobalsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cGlobalsVariableDeclarationParserRuleCall_1_0_0 = (RuleCall)cGlobalsAssignment_1_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//GlobalSection:
		//	"globals:" (globals+=VariableDeclaration ";")+;
		public ParserRule getRule() { return rule; }

		//"globals:" (globals+=VariableDeclaration ";")+
		public Group getGroup() { return cGroup; }

		//"globals:"
		public Keyword getGlobalsKeyword_0() { return cGlobalsKeyword_0; }

		//(globals+=VariableDeclaration ";")+
		public Group getGroup_1() { return cGroup_1; }

		//globals+=VariableDeclaration
		public Assignment getGlobalsAssignment_1_0() { return cGlobalsAssignment_1_0; }

		//VariableDeclaration
		public RuleCall getGlobalsVariableDeclarationParserRuleCall_1_0_0() { return cGlobalsVariableDeclarationParserRuleCall_1_0_0; }

		//";"
		public Keyword getSemicolonKeyword_1_1() { return cSemicolonKeyword_1_1; }
	}

	public class EventSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEventsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cEventsAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cEventsEventDeclParserRuleCall_1_0_0 = (RuleCall)cEventsAssignment_1_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//EventSection:
		//	"events:" (events+=EventDecl ";")+;
		public ParserRule getRule() { return rule; }

		//"events:" (events+=EventDecl ";")+
		public Group getGroup() { return cGroup; }

		//"events:"
		public Keyword getEventsKeyword_0() { return cEventsKeyword_0; }

		//(events+=EventDecl ";")+
		public Group getGroup_1() { return cGroup_1; }

		//events+=EventDecl
		public Assignment getEventsAssignment_1_0() { return cEventsAssignment_1_0; }

		//EventDecl
		public RuleCall getEventsEventDeclParserRuleCall_1_0_0() { return cEventsEventDeclParserRuleCall_1_0_0; }

		//";"
		public Keyword getSemicolonKeyword_1_1() { return cSemicolonKeyword_1_1; }
	}

	public class HandlerSectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HandlerSection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHandlersKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cHandlersAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHandlersHandlerDeclParserRuleCall_1_0 = (RuleCall)cHandlersAssignment_1.eContents().get(0);
		
		//HandlerSection:
		//	"handlers:" handlers+=HandlerDecl+;
		public ParserRule getRule() { return rule; }

		//"handlers:" handlers+=HandlerDecl+
		public Group getGroup() { return cGroup; }

		//"handlers:"
		public Keyword getHandlersKeyword_0() { return cHandlersKeyword_0; }

		//handlers+=HandlerDecl+
		public Assignment getHandlersAssignment_1() { return cHandlersAssignment_1; }

		//HandlerDecl
		public RuleCall getHandlersHandlerDeclParserRuleCall_1_0() { return cHandlersHandlerDeclParserRuleCall_1_0; }
	}

	public class ParamDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParamDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//ParamDeclaration:
		//	type=Type name=ID;
		public ParserRule getRule() { return rule; }

		//type=Type name=ID
		public Group getGroup() { return cGroup; }

		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//Type
		public RuleCall getTypeTypeEnumRuleCall_0_0() { return cTypeTypeEnumRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class EventDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EventDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cParamsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cParamsParamDeclarationParserRuleCall_2_0_0 = (RuleCall)cParamsAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cParamsParamDeclarationParserRuleCall_2_1_1_0 = (RuleCall)cParamsAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//EventDecl:
		//	name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")";
		public ParserRule getRule() { return rule; }

		//name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//(params+=ParamDeclaration ("," params+=ParamDeclaration)*)?
		public Group getGroup_2() { return cGroup_2; }

		//params+=ParamDeclaration
		public Assignment getParamsAssignment_2_0() { return cParamsAssignment_2_0; }

		//ParamDeclaration
		public RuleCall getParamsParamDeclarationParserRuleCall_2_0_0() { return cParamsParamDeclarationParserRuleCall_2_0_0; }

		//("," params+=ParamDeclaration)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }

		//params+=ParamDeclaration
		public Assignment getParamsAssignment_2_1_1() { return cParamsAssignment_2_1_1; }

		//ParamDeclaration
		public RuleCall getParamsParamDeclarationParserRuleCall_2_1_1_0() { return cParamsParamDeclarationParserRuleCall_2_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}

	public class HandlerDeclElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HandlerDecl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cParamsAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cParamsParamDeclarationParserRuleCall_2_0_0 = (RuleCall)cParamsAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cParamsAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cParamsParamDeclarationParserRuleCall_2_1_1_0 = (RuleCall)cParamsAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBodyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBodyAbstractBlockParserRuleCall_4_0 = (RuleCall)cBodyAssignment_4.eContents().get(0);
		
		//HandlerDecl:
		//	name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")" body=AbstractBlock;
		public ParserRule getRule() { return rule; }

		//name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")" body=AbstractBlock
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }

		//(params+=ParamDeclaration ("," params+=ParamDeclaration)*)?
		public Group getGroup_2() { return cGroup_2; }

		//params+=ParamDeclaration
		public Assignment getParamsAssignment_2_0() { return cParamsAssignment_2_0; }

		//ParamDeclaration
		public RuleCall getParamsParamDeclarationParserRuleCall_2_0_0() { return cParamsParamDeclarationParserRuleCall_2_0_0; }

		//("," params+=ParamDeclaration)*
		public Group getGroup_2_1() { return cGroup_2_1; }

		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }

		//params+=ParamDeclaration
		public Assignment getParamsAssignment_2_1_1() { return cParamsAssignment_2_1_1; }

		//ParamDeclaration
		public RuleCall getParamsParamDeclarationParserRuleCall_2_1_1_0() { return cParamsParamDeclarationParserRuleCall_2_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }

		//body=AbstractBlock
		public Assignment getBodyAssignment_4() { return cBodyAssignment_4; }

		//AbstractBlock
		public RuleCall getBodyAbstractBlockParserRuleCall_4_0() { return cBodyAbstractBlockParserRuleCall_4_0; }
	}

	public class AbstractBlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractBlock");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final RuleCall cCommandParserRuleCall_0_0 = (RuleCall)cGroup_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cCompoundAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cBodyAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cBodyAbstractBlockParserRuleCall_1_2_0 = (RuleCall)cBodyAssignment_1_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//// Block java-style
		//AbstractBlock:
		//	Command ";" | {Compound} "{" body+=AbstractBlock* "}";
		public ParserRule getRule() { return rule; }

		//Command ";" | {Compound} "{" body+=AbstractBlock* "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//Command ";"
		public Group getGroup_0() { return cGroup_0; }

		//Command
		public RuleCall getCommandParserRuleCall_0_0() { return cCommandParserRuleCall_0_0; }

		//";"
		public Keyword getSemicolonKeyword_0_1() { return cSemicolonKeyword_0_1; }

		//{Compound} "{" body+=AbstractBlock* "}"
		public Group getGroup_1() { return cGroup_1; }

		//{Compound}
		public Action getCompoundAction_1_0() { return cCompoundAction_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_1() { return cLeftCurlyBracketKeyword_1_1; }

		//body+=AbstractBlock*
		public Assignment getBodyAssignment_1_2() { return cBodyAssignment_1_2; }

		//AbstractBlock
		public RuleCall getBodyAbstractBlockParserRuleCall_1_2_0() { return cBodyAbstractBlockParserRuleCall_1_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }
	}

	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cVariableDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cVariableAssignParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBindHandlerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cUnbindHandlerParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cRaiseEventParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cPrintOutputParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cReadInputParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Command:
		//	VariableDeclaration | VariableAssign | BindHandler | UnbindHandler | RaiseEvent | PrintOutput | ReadInput;
		public ParserRule getRule() { return rule; }

		//VariableDeclaration | VariableAssign | BindHandler | UnbindHandler | RaiseEvent | PrintOutput | ReadInput
		public Alternatives getAlternatives() { return cAlternatives; }

		//VariableDeclaration
		public RuleCall getVariableDeclarationParserRuleCall_0() { return cVariableDeclarationParserRuleCall_0; }

		//VariableAssign
		public RuleCall getVariableAssignParserRuleCall_1() { return cVariableAssignParserRuleCall_1; }

		//BindHandler
		public RuleCall getBindHandlerParserRuleCall_2() { return cBindHandlerParserRuleCall_2; }

		//UnbindHandler
		public RuleCall getUnbindHandlerParserRuleCall_3() { return cUnbindHandlerParserRuleCall_3; }

		//RaiseEvent
		public RuleCall getRaiseEventParserRuleCall_4() { return cRaiseEventParserRuleCall_4; }

		//PrintOutput
		public RuleCall getPrintOutputParserRuleCall_5() { return cPrintOutputParserRuleCall_5; }

		//ReadInput
		public RuleCall getReadInputParserRuleCall_6() { return cReadInputParserRuleCall_6; }
	}

	public class PrintOutputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrintOutput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cOutputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOutputValueParserRuleCall_1_0 = (RuleCall)cOutputAssignment_1.eContents().get(0);
		
		//PrintOutput:
		//	"out" output=Value;
		public ParserRule getRule() { return rule; }

		//"out" output=Value
		public Group getGroup() { return cGroup; }

		//"out"
		public Keyword getOutKeyword_0() { return cOutKeyword_0; }

		//output=Value
		public Assignment getOutputAssignment_1() { return cOutputAssignment_1; }

		//Value
		public RuleCall getOutputValueParserRuleCall_1_0() { return cOutputValueParserRuleCall_1_0; }
	}

	public class ReadInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ReadInput");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInputAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cInputVariableDeclarationCrossReference_1_0 = (CrossReference)cInputAssignment_1.eContents().get(0);
		private final RuleCall cInputVariableDeclarationIDTerminalRuleCall_1_0_1 = (RuleCall)cInputVariableDeclarationCrossReference_1_0.eContents().get(1);
		
		//ReadInput:
		//	"in" input=[VariableDeclaration];
		public ParserRule getRule() { return rule; }

		//"in" input=[VariableDeclaration]
		public Group getGroup() { return cGroup; }

		//"in"
		public Keyword getInKeyword_0() { return cInKeyword_0; }

		//input=[VariableDeclaration]
		public Assignment getInputAssignment_1() { return cInputAssignment_1; }

		//[VariableDeclaration]
		public CrossReference getInputVariableDeclarationCrossReference_1_0() { return cInputVariableDeclarationCrossReference_1_0; }

		//ID
		public RuleCall getInputVariableDeclarationIDTerminalRuleCall_1_0_1() { return cInputVariableDeclarationIDTerminalRuleCall_1_0_1; }
	}

	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//VariableDeclaration:
		//	type=Type name=ID;
		public ParserRule getRule() { return rule; }

		//type=Type name=ID
		public Group getGroup() { return cGroup; }

		//type=Type
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }

		//Type
		public RuleCall getTypeTypeEnumRuleCall_0_0() { return cTypeTypeEnumRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}

	public class BindHandlerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BindHandler");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEventNameEventDeclCrossReference_0_0 = (CrossReference)cEventNameAssignment_0.eContents().get(0);
		private final RuleCall cEventNameEventDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cEventNameEventDeclCrossReference_0_0.eContents().get(1);
		private final Keyword cPlusSignEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHandlerNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cHandlerNameHandlerDeclCrossReference_2_0 = (CrossReference)cHandlerNameAssignment_2.eContents().get(0);
		private final RuleCall cHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1 = (RuleCall)cHandlerNameHandlerDeclCrossReference_2_0.eContents().get(1);
		
		//// subscribe the handler to the event
		//BindHandler:
		//	eventName=[EventDecl] "+=" handlerName=[HandlerDecl];
		public ParserRule getRule() { return rule; }

		//eventName=[EventDecl] "+=" handlerName=[HandlerDecl]
		public Group getGroup() { return cGroup; }

		//eventName=[EventDecl]
		public Assignment getEventNameAssignment_0() { return cEventNameAssignment_0; }

		//[EventDecl]
		public CrossReference getEventNameEventDeclCrossReference_0_0() { return cEventNameEventDeclCrossReference_0_0; }

		//ID
		public RuleCall getEventNameEventDeclIDTerminalRuleCall_0_0_1() { return cEventNameEventDeclIDTerminalRuleCall_0_0_1; }

		//"+="
		public Keyword getPlusSignEqualsSignKeyword_1() { return cPlusSignEqualsSignKeyword_1; }

		//handlerName=[HandlerDecl]
		public Assignment getHandlerNameAssignment_2() { return cHandlerNameAssignment_2; }

		//[HandlerDecl]
		public CrossReference getHandlerNameHandlerDeclCrossReference_2_0() { return cHandlerNameHandlerDeclCrossReference_2_0; }

		//ID
		public RuleCall getHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1() { return cHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1; }
	}

	public class UnbindHandlerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UnbindHandler");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEventNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEventNameEventDeclCrossReference_0_0 = (CrossReference)cEventNameAssignment_0.eContents().get(0);
		private final RuleCall cEventNameEventDeclIDTerminalRuleCall_0_0_1 = (RuleCall)cEventNameEventDeclCrossReference_0_0.eContents().get(1);
		private final Keyword cHyphenMinusEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cHandlerNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cHandlerNameHandlerDeclCrossReference_2_0 = (CrossReference)cHandlerNameAssignment_2.eContents().get(0);
		private final RuleCall cHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1 = (RuleCall)cHandlerNameHandlerDeclCrossReference_2_0.eContents().get(1);
		
		//// unsubscribe the handler to the event 
		//UnbindHandler:
		//	eventName=[EventDecl] "-=" handlerName=[HandlerDecl];
		public ParserRule getRule() { return rule; }

		//eventName=[EventDecl] "-=" handlerName=[HandlerDecl]
		public Group getGroup() { return cGroup; }

		//eventName=[EventDecl]
		public Assignment getEventNameAssignment_0() { return cEventNameAssignment_0; }

		//[EventDecl]
		public CrossReference getEventNameEventDeclCrossReference_0_0() { return cEventNameEventDeclCrossReference_0_0; }

		//ID
		public RuleCall getEventNameEventDeclIDTerminalRuleCall_0_0_1() { return cEventNameEventDeclIDTerminalRuleCall_0_0_1; }

		//"-="
		public Keyword getHyphenMinusEqualsSignKeyword_1() { return cHyphenMinusEqualsSignKeyword_1; }

		//handlerName=[HandlerDecl]
		public Assignment getHandlerNameAssignment_2() { return cHandlerNameAssignment_2; }

		//[HandlerDecl]
		public CrossReference getHandlerNameHandlerDeclCrossReference_2_0() { return cHandlerNameHandlerDeclCrossReference_2_0; }

		//ID
		public RuleCall getHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1() { return cHandlerNameHandlerDeclIDTerminalRuleCall_2_0_1; }
	}

	public class VariableAssignElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableAssign");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cNameVariableDeclarationCrossReference_0_0 = (CrossReference)cNameAssignment_0.eContents().get(0);
		private final RuleCall cNameVariableDeclarationIDTerminalRuleCall_0_0_1 = (RuleCall)cNameVariableDeclarationCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//VariableAssign:
		//	name=[VariableDeclaration] "=" value=Value;
		public ParserRule getRule() { return rule; }

		//name=[VariableDeclaration] "=" value=Value
		public Group getGroup() { return cGroup; }

		//name=[VariableDeclaration]
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//[VariableDeclaration]
		public CrossReference getNameVariableDeclarationCrossReference_0_0() { return cNameVariableDeclarationCrossReference_0_0; }

		//ID
		public RuleCall getNameVariableDeclarationIDTerminalRuleCall_0_0_1() { return cNameVariableDeclarationIDTerminalRuleCall_0_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=Value
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Value
		public RuleCall getValueValueParserRuleCall_2_0() { return cValueValueParserRuleCall_2_0; }
	}

	public class RaiseEventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RaiseEvent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRaiseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEventNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEventNameEventDeclCrossReference_1_0 = (CrossReference)cEventNameAssignment_1.eContents().get(0);
		private final RuleCall cEventNameEventDeclIDTerminalRuleCall_1_0_1 = (RuleCall)cEventNameEventDeclCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cParamsAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cParamsValueParserRuleCall_3_0_0 = (RuleCall)cParamsAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cParamsAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cParamsValueParserRuleCall_3_1_1_0 = (RuleCall)cParamsAssignment_3_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RaiseEvent:
		//	"raise" eventName=[EventDecl] "(" (params+=Value ("," params+=Value)*)? ")";
		public ParserRule getRule() { return rule; }

		//"raise" eventName=[EventDecl] "(" (params+=Value ("," params+=Value)*)? ")"
		public Group getGroup() { return cGroup; }

		//"raise"
		public Keyword getRaiseKeyword_0() { return cRaiseKeyword_0; }

		//eventName=[EventDecl]
		public Assignment getEventNameAssignment_1() { return cEventNameAssignment_1; }

		//[EventDecl]
		public CrossReference getEventNameEventDeclCrossReference_1_0() { return cEventNameEventDeclCrossReference_1_0; }

		//ID
		public RuleCall getEventNameEventDeclIDTerminalRuleCall_1_0_1() { return cEventNameEventDeclIDTerminalRuleCall_1_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//(params+=Value ("," params+=Value)*)?
		public Group getGroup_3() { return cGroup_3; }

		//params+=Value
		public Assignment getParamsAssignment_3_0() { return cParamsAssignment_3_0; }

		//Value
		public RuleCall getParamsValueParserRuleCall_3_0_0() { return cParamsValueParserRuleCall_3_0_0; }

		//("," params+=Value)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//params+=Value
		public Assignment getParamsAssignment_3_1_1() { return cParamsAssignment_3_1_1; }

		//Value
		public RuleCall getParamsValueParserRuleCall_3_1_1_0() { return cParamsValueParserRuleCall_3_1_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cREALTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBOOLTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Value returns ecore::EString:
		//	INT | REAL | BOOL;
		public ParserRule getRule() { return rule; }

		//INT | REAL | BOOL
		public Alternatives getAlternatives() { return cAlternatives; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//REAL
		public RuleCall getREALTerminalRuleCall_1() { return cREALTerminalRuleCall_1; }

		//BOOL
		public RuleCall getBOOLTerminalRuleCall_2() { return cBOOLTerminalRuleCall_2; }
	}
	
	
	public class TypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cT_INTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cT_INTIntKeyword_0_0 = (Keyword)cT_INTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cT_REALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cT_REALRealKeyword_1_0 = (Keyword)cT_REALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cT_BOOLEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cT_BOOLBoolKeyword_2_0 = (Keyword)cT_BOOLEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Type:
		//	T_INT="int" | T_REAL="real" | T_BOOL="bool";
		public EnumRule getRule() { return rule; }

		//T_INT="int" | T_REAL="real" | T_BOOL="bool"
		public Alternatives getAlternatives() { return cAlternatives; }

		//T_INT="int"
		public EnumLiteralDeclaration getT_INTEnumLiteralDeclaration_0() { return cT_INTEnumLiteralDeclaration_0; }

		//"int"
		public Keyword getT_INTIntKeyword_0_0() { return cT_INTIntKeyword_0_0; }

		//T_REAL="real"
		public EnumLiteralDeclaration getT_REALEnumLiteralDeclaration_1() { return cT_REALEnumLiteralDeclaration_1; }

		//"real"
		public Keyword getT_REALRealKeyword_1_0() { return cT_REALRealKeyword_1_0; }

		//T_BOOL="bool"
		public EnumLiteralDeclaration getT_BOOLEnumLiteralDeclaration_2() { return cT_BOOLEnumLiteralDeclaration_2; }

		//"bool"
		public Keyword getT_BOOLBoolKeyword_2_0() { return cT_BOOLBoolKeyword_2_0; }
	}
	
	private ProgramElements pProgram;
	private GlobalSectionElements pGlobalSection;
	private EventSectionElements pEventSection;
	private HandlerSectionElements pHandlerSection;
	private ParamDeclarationElements pParamDeclaration;
	private EventDeclElements pEventDecl;
	private HandlerDeclElements pHandlerDecl;
	private AbstractBlockElements pAbstractBlock;
	private CommandElements pCommand;
	private PrintOutputElements pPrintOutput;
	private ReadInputElements pReadInput;
	private VariableDeclarationElements pVariableDeclaration;
	private BindHandlerElements pBindHandler;
	private UnbindHandlerElements pUnbindHandler;
	private VariableAssignElements pVariableAssign;
	private RaiseEventElements pRaiseEvent;
	private TypeElements unknownRuleType;
	private ValueElements pValue;
	private TerminalRule tINT;
	private TerminalRule tREAL;
	private TerminalRule tBOOL;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public EventOrientedLanguageGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	/// *
	// * Main structure of a program. Global variables, events and handlers can be declared
	// * in any order but sections must stay separated. The init section must be the last one
	// * and it is mandatory.
	// * /Program:
	//	(globals=GlobalSection? & events=EventSection? & handlers=HandlerSection?) "init:" init=AbstractBlock "end";
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//GlobalSection:
	//	"globals:" (globals+=VariableDeclaration ";")+;
	public GlobalSectionElements getGlobalSectionAccess() {
		return (pGlobalSection != null) ? pGlobalSection : (pGlobalSection = new GlobalSectionElements());
	}
	
	public ParserRule getGlobalSectionRule() {
		return getGlobalSectionAccess().getRule();
	}

	//EventSection:
	//	"events:" (events+=EventDecl ";")+;
	public EventSectionElements getEventSectionAccess() {
		return (pEventSection != null) ? pEventSection : (pEventSection = new EventSectionElements());
	}
	
	public ParserRule getEventSectionRule() {
		return getEventSectionAccess().getRule();
	}

	//HandlerSection:
	//	"handlers:" handlers+=HandlerDecl+;
	public HandlerSectionElements getHandlerSectionAccess() {
		return (pHandlerSection != null) ? pHandlerSection : (pHandlerSection = new HandlerSectionElements());
	}
	
	public ParserRule getHandlerSectionRule() {
		return getHandlerSectionAccess().getRule();
	}

	//ParamDeclaration:
	//	type=Type name=ID;
	public ParamDeclarationElements getParamDeclarationAccess() {
		return (pParamDeclaration != null) ? pParamDeclaration : (pParamDeclaration = new ParamDeclarationElements());
	}
	
	public ParserRule getParamDeclarationRule() {
		return getParamDeclarationAccess().getRule();
	}

	//EventDecl:
	//	name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")";
	public EventDeclElements getEventDeclAccess() {
		return (pEventDecl != null) ? pEventDecl : (pEventDecl = new EventDeclElements());
	}
	
	public ParserRule getEventDeclRule() {
		return getEventDeclAccess().getRule();
	}

	//HandlerDecl:
	//	name=ID "(" (params+=ParamDeclaration ("," params+=ParamDeclaration)*)? ")" body=AbstractBlock;
	public HandlerDeclElements getHandlerDeclAccess() {
		return (pHandlerDecl != null) ? pHandlerDecl : (pHandlerDecl = new HandlerDeclElements());
	}
	
	public ParserRule getHandlerDeclRule() {
		return getHandlerDeclAccess().getRule();
	}

	//// Block java-style
	//AbstractBlock:
	//	Command ";" | {Compound} "{" body+=AbstractBlock* "}";
	public AbstractBlockElements getAbstractBlockAccess() {
		return (pAbstractBlock != null) ? pAbstractBlock : (pAbstractBlock = new AbstractBlockElements());
	}
	
	public ParserRule getAbstractBlockRule() {
		return getAbstractBlockAccess().getRule();
	}

	//Command:
	//	VariableDeclaration | VariableAssign | BindHandler | UnbindHandler | RaiseEvent | PrintOutput | ReadInput;
	public CommandElements getCommandAccess() {
		return (pCommand != null) ? pCommand : (pCommand = new CommandElements());
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}

	//PrintOutput:
	//	"out" output=Value;
	public PrintOutputElements getPrintOutputAccess() {
		return (pPrintOutput != null) ? pPrintOutput : (pPrintOutput = new PrintOutputElements());
	}
	
	public ParserRule getPrintOutputRule() {
		return getPrintOutputAccess().getRule();
	}

	//ReadInput:
	//	"in" input=[VariableDeclaration];
	public ReadInputElements getReadInputAccess() {
		return (pReadInput != null) ? pReadInput : (pReadInput = new ReadInputElements());
	}
	
	public ParserRule getReadInputRule() {
		return getReadInputAccess().getRule();
	}

	//VariableDeclaration:
	//	type=Type name=ID;
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return (pVariableDeclaration != null) ? pVariableDeclaration : (pVariableDeclaration = new VariableDeclarationElements());
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}

	//// subscribe the handler to the event
	//BindHandler:
	//	eventName=[EventDecl] "+=" handlerName=[HandlerDecl];
	public BindHandlerElements getBindHandlerAccess() {
		return (pBindHandler != null) ? pBindHandler : (pBindHandler = new BindHandlerElements());
	}
	
	public ParserRule getBindHandlerRule() {
		return getBindHandlerAccess().getRule();
	}

	//// unsubscribe the handler to the event 
	//UnbindHandler:
	//	eventName=[EventDecl] "-=" handlerName=[HandlerDecl];
	public UnbindHandlerElements getUnbindHandlerAccess() {
		return (pUnbindHandler != null) ? pUnbindHandler : (pUnbindHandler = new UnbindHandlerElements());
	}
	
	public ParserRule getUnbindHandlerRule() {
		return getUnbindHandlerAccess().getRule();
	}

	//VariableAssign:
	//	name=[VariableDeclaration] "=" value=Value;
	public VariableAssignElements getVariableAssignAccess() {
		return (pVariableAssign != null) ? pVariableAssign : (pVariableAssign = new VariableAssignElements());
	}
	
	public ParserRule getVariableAssignRule() {
		return getVariableAssignAccess().getRule();
	}

	//RaiseEvent:
	//	"raise" eventName=[EventDecl] "(" (params+=Value ("," params+=Value)*)? ")";
	public RaiseEventElements getRaiseEventAccess() {
		return (pRaiseEvent != null) ? pRaiseEvent : (pRaiseEvent = new RaiseEventElements());
	}
	
	public ParserRule getRaiseEventRule() {
		return getRaiseEventAccess().getRule();
	}

	//enum Type:
	//	T_INT="int" | T_REAL="real" | T_BOOL="bool";
	public TypeElements getTypeAccess() {
		return (unknownRuleType != null) ? unknownRuleType : (unknownRuleType = new TypeElements());
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//Value returns ecore::EString:
	//	INT | REAL | BOOL;
	public ValueElements getValueAccess() {
		return (pValue != null) ? pValue : (pValue = new ValueElements());
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return (tINT != null) ? tINT : (tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "INT"));
	} 

	//terminal REAL returns ecore::EDouble:
	//	"0".."9"* ("." "0".."9"+)?;
	public TerminalRule getREALRule() {
		return (tREAL != null) ? tREAL : (tREAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "REAL"));
	} 

	//terminal BOOL returns ecore::EBoolean:
	//	"true" | "false";
	public TerminalRule getBOOLRule() {
		return (tBOOL != null) ? tBOOL : (tBOOL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BOOL"));
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" | "n" |
	//	"f" | "r" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
