/*
 * generated by Xtext
 */
package org.mt.lic.eol;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EventOrientedLanguageRuntimeModule extends org.mt.lic.eol.AbstractEventOrientedLanguageRuntimeModule {

}
