/*
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */

#include "Handler.h"

Handler::Handler() {};

Handler::~Handler() {};

void Handler::setEvent(Event* _event) {
    this->_event = _event;
}

Event* Handler::getEvent() const {
    return _event;
}
