/*
 * Event Oriented Language
 * Autogenerated code
 * Do not modify it
 */

#ifndef _HANDLER_H
#define	_HANDLER_H

#include "Event.h"

using namespace std;

class Event;

class Handler {
public:
    Handler();
    ~Handler();
    virtual void update(void* args) = 0;
	void setEvent(Event* e);
    Event* getEvent() const;
private:
    Event* _event;
};

#endif	/* _HANDLER_H */
